In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv('../course_notebooks/08-Linear-Regression-Models/Advertising.csv')
x=df.drop('sales',axis=1)
y=df['sales']

In [2]:
from sklearn.preprocessing import PolynomialFeatures
polynomial_converter = PolynomialFeatures(3, include_bias=False)
poly_features = polynomial_converter.fit_transform(x)

In [3]:
from sklearn.model_selection import train_test_split
x_tr, x_te, y_tr, y_te = train_test_split(poly_features,y,test_size=0.3,random_state=101)

In [4]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()

In [5]:
scaler.fit(x_tr)
x_train=scaler.transform(x_tr)
x_test=scaler.transform(x_te)
x_train[0]

array([ 0.49300171, -0.33994238,  1.61586707,  0.28407363, -0.02568776,
        1.49677566, -0.59023161,  0.41659155,  1.6137853 ,  0.08057172,
       -0.05392229,  1.01524393, -0.36986163,  0.52457967,  1.48737034,
       -0.66096022, -0.16360242,  0.54694754,  1.37075536])

# Ridge

In [15]:
from sklearn.linear_model import Ridge
ridge_model=Ridge(alpha=20)
ridge_model.fit(x_train,y_tr)
test_predictions = ridge_model.predict(x_test)
from sklearn.metrics import mean_absolute_error, mean_squared_error
mae = mean_absolute_error(y_te, test_predictions)
rmse = np.sqrt(mean_squared_error(y_te, test_predictions))
print(mae)
print(rmse)


0.6563690894367935
1.0326373897987993


In [28]:
from sklearn.linear_model import RidgeCV
from sklearn.metrics import mean_absolute_error, mean_squared_error
rcv=RidgeCV(alphas=(0.1,1.0,10.0),scoring='neg_mean_absolute_error')
rcv.fit(x_train,y_tr)
print(rcv.alpha_)
test_predictions = rcv.predict(x_test)
mae = mean_absolute_error(y_te, test_predictions)
rmse = np.sqrt(mean_squared_error(y_te, test_predictions))
print(mae)
print(rmse)
print(rcv.best_score_)

0.1
0.42737748843643875
0.6180719926971409
-0.3749223340292948


In [29]:
from sklearn.metrics import SCORERS
SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'matthews_corrcoef', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_absolute_percentage_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'top_k_accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'positive_likelihood_ratio', 'neg_negative_likelihood_ratio', 'adjusted_rand_score', 'rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weig

# Lasso

In [39]:
from sklearn.linear_model import LassoCV
lasso_model=LassoCV(eps=0.001,n_alphas=100,cv=5,max_iter=100000)
#lasso_model=LassoCV(eps=0.1,n_alphas=100,cv=5)
lasso_model.fit(x_train,y_tr)
print(lasso_model.alpha_)
test_predictions = lasso_model.predict(x_test)
mae = mean_absolute_error(y_te, test_predictions)
rmse = np.sqrt(mean_squared_error(y_te, test_predictions))
print(mae)
print(rmse)
lasso_model.coef_

0.004943070909225833
0.4335034618590074
0.6063140748984044


array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])

# Elastic Net

In [44]:
from sklearn.linear_model import ElasticNetCV
elastic_model=ElasticNetCV(l1_ratio=[.1,.5,.9,.95,.99,1],eps=0.001,n_alphas=100,cv=5,max_iter=100000)
elastic_model.fit(x_train,y_tr)
print(elastic_model.alpha_)
test_predictions = elastic_model.predict(x_test)
mae = mean_absolute_error(y_te, test_predictions)
rmse = np.sqrt(mean_squared_error(y_te, test_predictions))
print(mae)
print(rmse)
print(elastic_model.l1_ratio_)
elastic_model.coef_

0.004943070909225833
0.4335034618590074
0.6063140748984044
1.0


array([ 4.86023329,  0.12544598,  0.20746872, -4.99250395,  4.38026519,
       -0.22977201, -0.        ,  0.07267717, -0.        ,  1.77780246,
       -0.69614918, -0.        ,  0.12044132, -0.        , -0.        ,
       -0.        ,  0.        ,  0.        , -0.        ])