In [1]:
import numpy as np

In [8]:
l = [1,2,3]
type(l)

list

In [14]:
a = np.array(l)
type(a)

numpy.ndarray

In [23]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(matrix)


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
np.arange(0,101,20)


array([  0,  20,  40,  60,  80, 100])

In [35]:
np.zeros((2,5))


array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [37]:
np.ones((4,3))


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
print(np.linspace(0,10,3))
print(np.linspace(0,10,40 ))


[ 0.  5. 10.]
[ 0.          0.25641026  0.51282051  0.76923077  1.02564103  1.28205128
  1.53846154  1.79487179  2.05128205  2.30769231  2.56410256  2.82051282
  3.07692308  3.33333333  3.58974359  3.84615385  4.1025641   4.35897436
  4.61538462  4.87179487  5.12820513  5.38461538  5.64102564  5.8974359
  6.15384615  6.41025641  6.66666667  6.92307692  7.17948718  7.43589744
  7.69230769  7.94871795  8.20512821  8.46153846  8.71794872  8.97435897
  9.23076923  9.48717949  9.74358974 10.        ]


In [3]:
np.eye(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.random.rand(1)


array([0.23432388])

In [11]:
np.random.rand(4,8)


array([[0.07050444, 0.06429771, 0.27920663, 0.5270935 , 0.11457934,
        0.97653291, 0.57829145, 0.37518304],
       [0.96444105, 0.88862687, 0.55745639, 0.98036204, 0.26424026,
        0.00842335, 0.2029473 , 0.60607794],
       [0.37970429, 0.28033404, 0.24154643, 0.01771341, 0.12902625,
        0.38353806, 0.93910133, 0.68020149],
       [0.89276764, 0.62966244, 0.09032432, 0.76949664, 0.66175469,
        0.60629164, 0.45922396, 0.69549719]])

In [14]:
np.random.randn(2,3)


array([[-0.42596855, -0.75277386,  1.23427677],
       [-0.38198563,  0.51736767,  0.07112383]])

In [19]:
np.random.randint(0,101,(5,4))
np.random.randint(0,101,4)


array([79,  5,  9, 73])

In [25]:
np.random.seed(42)
np.random.random(4)


array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [49]:
a = np.arange(0,25)
print(a)
a.reshape(5,5)
r = np.random.randint(0,3000,(10,4))
print("max found at index {}: {}".format(r.argmax(), r.max()))
print("min found at index {}: {}".format(r.argmin(), r.min()))
print(r.dtype)
print(r.shape)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]
max found at index 11: 2923
min found at index 17: 38
int32
(10, 4)


In [66]:
b = np.arange(0,25)
c = b.copy()
print(b[8])
print(b[1:8])
print(b[:8])
print(b[8:])

b[2:4]=100
print(b)

slice = b[7:10]
print(slice)
b[8]=40
print(slice)
slice[:]=-1
print(slice)
print(b)
print(c)


8
[1 2 3 4 5 6 7]
[0 1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24]
[  0   1 100 100   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24]
[7 8 9]
[ 7 40  9]
[-1 -1 -1]
[  0   1 100 100   4   5   6  -1  -1  -1  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24]


In [90]:
g = np.arange(5,50,5).reshape(3,3)
print(type(g))
print(g)
print(g[1])
print(g[1,1])
print(g[0,2])
print(g[1][1])
print(g[:2])
print(g[:2,1:])
print(g[:2,1:] > 13)
print(g[g > 13])
print(len(g[g > 13]))


<class 'numpy.ndarray'>
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
[20 25 30]
25
15
25
[[ 5 10 15]
 [20 25 30]]
[[10 15]
 [25 30]]
[[False  True]
 [ True  True]]
[15 20 25 30 35 40 45]
7


In [15]:
arr = np.arange(0,10)
print(arr + arr)
print(arr - arr)
print(arr / arr)
print(arr + 5)
print(1/arr)
print(np.sqrt(arr))
print(np.sin(arr))
print(arr.sum())
print(arr.mean())
print(arr.max())
print(arr.var())
print(arr.std())

[ 0  2  4  6  8 10 12 14 16 18]
[0 0 0 0 0 0 0 0 0 0]
[nan  1.  1.  1.  1.  1.  1.  1.  1.  1.]
[ 5  6  7  8  9 10 11 12 13 14]
[       inf 1.         0.5        0.33333333 0.25       0.2
 0.16666667 0.14285714 0.125      0.11111111]
[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.        ]
[ 0.          0.84147098  0.90929743  0.14112001 -0.7568025  -0.95892427
 -0.2794155   0.6569866   0.98935825  0.41211849]
45
4.5
9
8.25
2.8722813232690143


F:\Dev\python\course\venv\lib\site-packages\ipykernel_launcher.py:4: RuntimeWarning: invalid value encountered in true_divide
  after removing the cwd from sys.path.
F:\Dev\python\course\venv\lib\site-packages\ipykernel_launcher.py:6: RuntimeWarning: divide by zero encountered in true_divide
  


In [20]:
d = np.arange(0,25).reshape(5,5)
print(d)
print(d.sum(axis=0))
print(d.sum(axis=1))
print(d.mean(axis=1))


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[50 55 60 65 70]
[ 10  35  60  85 110]
[ 2.  7. 12. 17. 22.]
