In [32]:
import numpy as np
import pandas as pd

In [33]:
# first.readlines()
# first.read()
def count_words(document,document_vocabulary,total_vocabulary):
    words = document.read().lower().split()
    for word in words:
        document_occurrences = document_vocabulary.setdefault(word,0)
        document_vocabulary[word] = document_occurrences + 1
        total_occurrences = total_vocabulary.setdefault(word,0)
        total_vocabulary[word] = total_occurrences + 1

In [34]:
total_vocabulary = {}
first_vocabulary = {}
second_vocabulary = {}
with open('One.txt') as first, open('Two.txt') as second:
    count_words(first,first_vocabulary,total_vocabulary)
    count_words(second,second_vocabulary,total_vocabulary)
unique_word_count = len(total_vocabulary.keys())
print(f'unique word count: {unique_word_count}')
total_vocabulary

unique word count: 19


{'this': 2,
 'is': 4,
 'a': 2,
 'story': 2,
 'about': 2,
 'dogs': 2,
 'our': 1,
 'canine': 1,
 'pets': 1,
 'are': 1,
 'furry': 1,
 'animals': 1,
 'surfing': 2,
 'catching': 1,
 'waves': 1,
 'fun': 1,
 'popular': 1,
 'water': 1,
 'sport': 1}

In [35]:
def add_word_counts(words,document_frequencies,full_vocabulary):
    for word in words:
        word_index = full_vocabulary[word]
        document_frequencies[word_index] +=1
with open('One.txt') as first, open('Two.txt') as second:
    first_words = first.read().lower().split()
    second_words = second.read().lower().split()
all_uni_words = set()
all_uni_words.update(set(first_words))
all_uni_words.update(set(second_words))
full_vocabulary = dict()
i = 0
for word in all_uni_words:
    full_vocabulary[word] = i
    i = i + 1
one_freq = [0]*len(all_uni_words)
two_freq = [0]*len(all_uni_words)
all_words = ['']*len(all_uni_words)
add_word_counts(first_words,one_freq,full_vocabulary)
add_word_counts(second_words,two_freq,full_vocabulary)
bag_of_words = pd.DataFrame(data=[one_freq,two_freq],columns=full_vocabulary.keys())

In [36]:
bag_of_words

story  this  water  are  dogs  about  fun  canine  is  our  catching  \
0      1     1      0    1     2      1    0       1   1    1         0   
1      1     1      1    0     0      1    1       0   3    0         1   

   furry  waves  popular  a  pets  sport  surfing  animals  
0      1      0        0  1     1      0        0        1  
1      0      1        1  1     0      1        2        0

In [37]:
text = ['This is a line',
        'This is another line',
        'Completely different line']

In [49]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
# cv = CountVectorizer(stop_words='english')
sparse_matrix = cv.fit_transform(text)

In [50]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]], dtype=int64)

In [51]:
cv.vocabulary_ # indices of words in sparse matrix

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [55]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer()
results = tfidf.fit_transform(sparse_matrix)
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
vectorizer.fit_transform(text).todense()


matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])